package com.ir.formgenerator.service.impl;

import com.ir.formgenerator.model.FormRecord;
import com.ir.formgenerator.service.PdfGeneratorService;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.UnitValue;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.Map;


@Service
public class PdfGeneratorServiceImpl implements PdfGeneratorService {

    private static final Logger log = LoggerFactory.getLogger(PdfGeneratorServiceImpl.class);

    @Override
    public byte[] generate(List<FormRecord> records) {
        log.info("Generating PDF for {} record(s)", records.size());

        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            PdfWriter writer = new PdfWriter(out);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document document = new Document(pdfDoc);

            // Title
            document.add(new Paragraph("Form Generator Report")
                    .setBold()
                    .setFontSize(18)
                    .setMarginBottom(10));

            document.add(new Paragraph("Generated by Intelligent Reporting (IR)")
                    .setFontSize(10)
                    .setMarginBottom(20));

            if (records.isEmpty()) {
                document.add(new Paragraph("No records found in the CSV file."));
            } else {
                // Build a table from the first record's field keys as column headers
                Map<String, String> firstFields = records.get(0).getFields();
                int columnCount = firstFields.size();

                Table table = new Table(UnitValue.createPercentArray(columnCount))
                        .useAllAvailableWidth();

                // Header row
                for (String header : firstFields.keySet()) {
                    table.addHeaderCell(
                            new Cell().add(new Paragraph(header).setBold())
                                    .setBackgroundColor(ColorConstants.LIGHT_GRAY));
                }

                // Data rows
                for (FormRecord record : records) {
                    for (String value : record.getFields().values()) {
                        table.addCell(new Cell().add(new Paragraph(value)));
                    }
                }

                document.add(table);
            }

            document.close();
            log.info("PDF generation complete, size: {} bytes", out.size());
            return out.toByteArray();

        } catch (Exception e) {
            log.error("PDF generation failed", e);
            throw new RuntimeException("Failed to generate PDF", e);
        }
    }
}
